export enum FormError {
    INVALID_FIELDS = 'INVALID_FIELDS',
    INVALID_EMAIL = 'INVALID_EMAIL',
    USERNAME_TAKEN = 'USERNAME_TAKEN',
    EMAIL_TAKEN = 'EMAIL_TAKEN',
    INCORRECT_PASSWORD = 'INCORRECT_PASSWORD'
}